server {
    listen 80;
    listen [::]:80;
    server_name _;  # This will match all hostnames

    root /usr/share/nginx/html/;
    index index.html index.htm;

    access_log /var/log/nginx/access.log main;

    location / {
        try_files $uri $uri/ /index.html =404;
        access_log on;
        expires 1d;
        add_header Cache-Control public;
        add_header Cache-Control immutable;
        autoindex off;
    }

    error_page 404 /404.html;

    error_page 405 =200 @405;
    location @405 {
        root /usr/share/nginx/html/;
        index index.html index.htm;
    }
}
